patch apex
NVIDIA/PyProf pull request #110
Opened 2020-10-29 16:34 UTC by tgerdesnv

Added a number of apex C modules to patch
Patched most of apex python modules  (only classes in the modules, and only forward/backward/step functions in those classes)

2020-10-29 21:15 UTC, adityaiitb commented
I think we should now refactor the code and move apex patching to a separate file and class. The logic is very custom and there are quite a few `apex*` functions.

2020-10-30 18:51 UTC, debermudez requested changes

2020-10-30 18:51 UTC, debermudez commented on pyprof/nvtx/nvmarker.py
> +def patch_apex_pyt():
Can we add a docstring to this? 
Something like patching all apex pytorch methods or whatever this is actually doing?

2020-10-30 18:55 UTC, debermudez approved these changes

2020-10-30 20:53 UTC, merged